DATASET:
 TRAIN: 'data/filtered_data/train_data.json'
 VAL: 'data/filtered_data/test_data.json'

MODEL:
  NAME: "cgcnn"
  PRETRAINED_MODEL_PATH: " " # NOT EXIST
  INIT_FILE: 'cif_file/atom_init.json'
  CIF_FOLDER: "cif_file"

SOLVER:
  LR: 0.01
  EPOCHS: 100
  NUM_RUNS: 50

CGCNN:
    FEATURE_FUSION: 'none'

LOGGING:
  LOG_DIR: "saved_models"
  LOG_DIR_NAME: "cgcnn"
