DATASET:
  TRAIN: 'data/fine_tune/train_data_10.json'
  VAL: 'data/fine_tune/test_data.json'

MODEL:
  NAME: "random_forest"
  PRETRAINED_MODEL_PATH: ""
  INIT_FILE: "cif_file/atom_init.json"
  CIF_FOLDER: "cif_file"
  MAX_NBRS: 12
  RADIUS: 8.0
  HYPERPARAMS:
    SEARCH: grid
    n_estimators: [200, 400, 800]
    max_depth: [null, 10, 20]
    min_samples_split: [2, 4, 8]
    min_samples_leaf: [1, 2, 4]

SOLVER:
  SEED: 42
  NUM_FOLDS: 10
  EPOCHS: 1
  RANDOMIZE: False

LOGGING:
  LOG_DIR: "saved_models"
  LOG_DIR_NAME: "train_from_scratch/random_forest_10"
