DATASET:
 TRAIN: 'data/filtered_data/train_data.json'
 VAL: 'data/filtered_data/test_data.json'

MODEL:
  NAME: 'random_forest'
  PRETRAINED_MODEL_PATH: ' '  # NOT EXIST
  INIT_FILE: 'cif_file/atom_init.json'
  CIF_FOLDER: "cif_file"


LOGGING:
  LOG_DIR: "saved_models"
  LOG_DIR_NAME: " "
