DATASET:
  TRAIN: ""
  VAL: ""
  PREDEFINED_SPLIT: True
  SPLIT_GLOB: "data/domain_split/periodictablegroups_split/*.train.json"

SOLVER:
  SEED: 42
  EPOCHS: 100
  LR: 0.001
  NUM_FOLDS: 10
  RANDOMIZE: True

MODEL:
  NAME: "cartnet"
  PRETRAINED_MODEL_PATH: "saved_models/cartnet/best.ckpt"
  INIT_FILE: "cif_file/atom_init.json"
  CIF_FOLDER: "cif_file"
  MAX_NBRS: 12
  RADIUS: 8.0

CARTNET:
  ENCODING: z
  DIM_IN: 256
  DIM_RBF: 64
  NUM_LAYERS: 4
  INVARIANT: True
  USE_ENVELOPE: True
  ATOM_TYPES: True

LOGGING:
  LOG_DIR: "saved_models"
  LOG_DIR_NAME: "split_json/cartnet/periodictablegroups"
