DATASET:
  TRAIN: ""
  VAL: ""
  PREDEFINED_SPLIT: True
  SPLIT_GLOB: "data/split_json/periodictablegroups_split/*.train.json"

MODEL:
  NAME: "alignn"
  PRETRAINED_MODEL_PATH: "saved_models/pretrain/alignn/best.ckpt"
  INIT_FILE: "cif_file/atom_init.json"
  CIF_FOLDER: "cif_file"

SOLVER:
  LR: 0.001
  NUM_FOLDS: 10
  EPOCHS: 50
  NUM_RUNS: 1

ALIGNN:
  HIDDEN_DIM: 160
  NUM_LAYERS: 6
  NUM_RBF: 64
  DROPOUT: 0.05
  READOUT: "mean"
  ACTIVATION: "silu"
  RBF_TRAINABLE: False
  MAX_NEIGHBORS: 1000
  ENCODING: "z"
  MAX_NUM_ELEMENTS: 94

LOGGING:
  LOG_DIR: "saved_models"
  LOG_DIR_NAME: "split_json/alignn/periodictablegroups"
