DATASET:
  TRAIN: "data/pretrain_data.json"
  VAL: "data/fine_tune/test_data.json"

MODEL:
  NAME: "chgnet"
  PRETRAINED_MODEL_PATH: ""
  INIT_FILE: "cif_file/atom_init.json"
  CIF_FOLDER: "cif_file"

SOLVER:
  LR: 0.01
  NUM_FOLDS: 10
  EPOCHS: 200
  NUM_RUNS: 1
  BATCH_SIZE: 32

CHGNET:
  ENCODING: "prop"
  ATOM_GRAPH_CUTOFF: 8.0
  BOND_GRAPH_CUTOFF: 3.0
  ATOM_INPUT_DIM: 92
  MAX_NUM_ELEMENTS: 94

LOGGING:
  LOG_DIR: "saved_models"
  LOG_DIR_NAME: "pretrain/chgnet_prop"

OUTPUT:
  LOOP_RESULTS: "result/chgnet_prop_pretrain/loop.csv"
  PREDICTIONS: "result/chgnet_prop_pretrain/predict.csv"
