DATASET:
  TRAIN: "data/pretrain_data.json"
  VAL: "data/fine_tune/test_data.json"

MODEL:
  NAME: "chgnet"
  PRETRAINED_MODEL_PATH: "saved_models/pretrain/chgnet_z/pretrain-last-epoch=91.ckpt"
  INIT_FILE: "cif_file/atom_init.json"
  CIF_FOLDER: "cif_file"

SOLVER:
  LR: 0.001
  NUM_FOLDS: 10
  EPOCHS: 200

CHGNET:
  ENCODING: "z"

LOGGING:
  LOG_DIR: "saved_models"
  LOG_DIR_NAME: "pretrain/chgnet_z"
