DATASET:
  TRAIN: ""
  VAL: ""
  PREDEFINED_SPLIT: True
  SPLIT_GLOB: "data/split_json/periodictablegroups_split/*.train.json"

MODEL:
  NAME: "alignn"
  PRETRAINED_MODEL_PATH: ""
  INIT_FILE: "cif_file/atom_init.json"
  CIF_FOLDER: "cif_file"

SOLVER:
  LR: 0.001
  NUM_FOLDS: 10
  EPOCHS: 50
  NUM_RUNS: 1


LOGGING:
  LOG_DIR: "saved_models"
  LOG_DIR_NAME: "split_json/alignn_prop/periodictablegroups_nopretrain"
