DATASET:
  TRAIN: ''
  VAL: ''
  PREDEFINED_SPLIT: true
  SPLIT_GLOB: data/split_by_category/*.train.json
MODEL:
  NAME: alignn
  PRETRAINED_MODEL_PATH: ''
  INIT_FILE: cif_file/atom_init.json
  CIF_FOLDER: cif_file
SOLVER:
  LR: 0.001
  NUM_FOLDS: 10
  EPOCHS: 100
  NUM_RUNS: 1
  BATCH_SIZE: 32
ALIGNN:
  HIDDEN_DIM: 160
  NUM_LAYERS: 6
  NUM_RBF: 64
  DROPOUT: 0.05
  READOUT: mean
  ACTIVATION: silu
  RBF_TRAINABLE: false
  MAX_NEIGHBORS: 1000
  ENCODING: prop
  MAX_NUM_ELEMENTS: 94
LOGGING:
  LOG_DIR: saved_models
  LOG_DIR_NAME: split_by_category/alignn_prop_no_pretrain
