DATASET:
  TRAIN: ''
  VAL: ''
  PREDEFINED_SPLIT: true
  SPLIT_GLOB: data/split_by_category/*.train.json
MODEL:
  NAME: random_forest
  PRETRAINED_MODEL_PATH: ''
  INIT_FILE: cif_file/atom_init.json
  CIF_FOLDER: cif_file
  HYPERPARAMS:
    SEARCH: grid
    n_estimators:
    - 200
    - 400
    - 800
    max_depth:
    - null
    - 10
    - 20
    min_samples_split:
    - 2
    - 4
    - 8
    min_samples_leaf:
    - 1
    - 2
    - 4
SOLVER:
  NUM_FOLDS: 10
  EPOCHS: 100
LOGGING:
  LOG_DIR: saved_models
  LOG_DIR_NAME: split_by_category/random_forest
