DATASET:
  TRAIN: data/splits_feature_ood/train_data.json
  VAL: data/splits_feature_ood/test_data.json
MODEL:
  NAME: chgnet
SOLVER:
  LR: 0.001
  NUM_FOLDS: 10
  EPOCHS: 100
CHGNET:
  ENCODING: prop
LOGGING:
  LOG_DIR: saved_models
  LOG_DIR_NAME: feature_ood/chgnet_prop_no_pretrain
