DATASET:
  TRAIN: "data/fine_tune/train_data_10.json"
  VAL: "data/fine_tune/test_data.json"

MODEL:
  NAME: "alignn"
  PRETRAINED_MODEL_PATH: "saved_models/pretrain/alignn_z/best.ckpt"
  INIT_FILE: "cif_file/atom_init.json"
  CIF_FOLDER: "cif_file"

ALIGNN:
  ENCODING: "z"

SOLVER:
  LR: 0.001
  NUM_FOLDS: 10
  EPOCHS: 100


LOGGING:
  LOG_DIR: "saved_models"
  LOG_DIR_NAME: "alignn_z_10"
