DATASET:
  TRAIN: "data/pretrain_data.json"
  VAL: 'data/fine_tune/test_data.json'
MODEL:
  NAME: "leftnet"
  PRETRAINED_MODEL_PATH: ""
  INIT_FILE: "cif_file/atom_init.json"
  CIF_FOLDER: "cif_file"

SOLVER:
  LR: 0.001
  EPOCHS: 200

LEFTNET:
  ENCODING: 'prop'

LOGGING:
  LOG_DIR: "saved_models"
  LOG_DIR_NAME: "pretrain/leftnet_prop"
