DATASET:
  TRAIN: ""
  VAL: ""
  PREDEFINED_SPLIT: True
  SPLIT_GLOB: "data/domain_split/chemsys_split/*.train.json"

MODEL:
  NAME: "cgcnn"
  PRETRAINED_MODEL_PATH: "saved_models/cgcnn/best-mre-epoch=173-val_mre=0.2282.ckpt"
  INIT_FILE: "cif_file/atom_init.json"
  CIF_FOLDER: "cif_file"
  RADIUS: 8.0

SOLVER:
  EPOCHS: 50
  NUM_FOLDS: 10

CGCNN:
  FEATURE_FUSION: "none"
  LAYER_FREEZE: "none"

LOGGING:
  LOG_DIR: "saved_models"
  LOG_DIR_NAME: "split_json/cgcnn/chemsys"
