DATASET:
  TRAIN: ""
  VAL: ""
  PREDEFINED_SPLIT: True
  SPLIT_GLOB: "data/split_json/chemsys_split/*.train.json"

MODEL:
  NAME: "chgnet"
  PRETRAINED_MODEL_PATH: "saved_models/pretrain/chgnet_prop/best.ckpt"
  INIT_FILE: "cif_file/atom_init.json"
  CIF_FOLDER: "cif_file"

SOLVER:
  LR: 0.001
  NUM_FOLDS: 10
  EPOCHS: 50

CHGNET:
  ATOM_FEA_DIM: 64
  BOND_FEA_DIM: 64
  ANGLE_FEA_DIM: 64
  NUM_RADIAL: 31
  NUM_ANGULAR: 31
  N_CONV: 4
  ATOM_CONV_HIDDEN_DIM: 64
  BOND_CONV_HIDDEN_DIM: 64
  ANGLE_LAYER_HIDDEN_DIM: 0
  CONV_DROPOUT: 0.0
  READ_OUT: "ave"
  MLP_HIDDEN_DIMS: (64, 64, 64)
  MLP_DROPOUT: 0.0
  MLP_FIRST: True
  IS_INTENSIVE: True
  NON_LINEARITY: "silu"
  ATOM_GRAPH_CUTOFF: 6.0
  BOND_GRAPH_CUTOFF: 3.0
  CUTOFF_COEFF: 8
  LEARNABLE_RBF: True
  GMLP_NORM: "layer"
  READOUT_NORM: "layer"
  ENCODING: "prop"
  ATOM_INPUT_DIM: 92
  MAX_NUM_ELEMENTS: 94

LOGGING:
  LOG_DIR: "saved_models"
  LOG_DIR_NAME: "split_json/chgnet_prop/chemsys"
